# One CLI to format the code tree - https://github.com/numtide/treefmt
excludes = [ "*.lock", "*.conf", "justfile" ]

[formatter.nixfmt]
command = "nixfmt"
includes = [ "*.nix" ]
priority = 0

[formatter.yamlfmt]
command = "yamlfmt"
includes = [ "*.yaml", "*.yml" ]
priority = 0

# TODO: TOML
